### ISSUE TITLE
Implement a way to transfer existing rules back and forth

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/rules_cmi#2]
Ideally, there should be some admin configuration that allows someone to move all DB rules to CMI rules and vice versa. This is important so that Rules are not lost when enabling or disabling this module. 

Ideally this should be done automatically, but it'd be safer to have this as a manual option.

**Comment by herbdool** [comment]
I haven't tried it but it's looking pretty good so far @argiepiano. Module is smaller than I expected!

**Comment by argiepiano** [comment]
> Module is smaller than I expected!

Thanks. Yes, some of the "heavy lifting" is done by Entity Plus CMI.

**Comment by argiepiano** [comment]
DB to CMI already added in PR https://github.com/backdrop-contrib/rules_cmi/pull/6
