### ISSUE TITLE
Notice: Undefined property: EntityPlusCmiEntity::$feed_node in RulesEntityCmiController->attachLoad() 

### ISSUE THREAD

**Issue by nattywebdev** [backdrop-contrib/rules_cmi#27]
I'm using this module on a site and am seeing this message when I run update.php:

`Notice: Undefined property: EntityPlusCmiEntity::$feed_node in RulesEntityCmiController->attachLoad() (line 43 of /home/xxxxxxxxxxx/public_html/modules/rules_cmi/includes/RulesEntityCmiController.inc).`

I think the module is working correctly but I wonder what this means - can you suggest the cause please @argiepiano ?

**Comment by argiepiano** [comment]
Hi @nattywebdev. Yes, sorry. You mentioned this already before. I will tackle this issue in the next few days.

**Comment by nattywebdev** [comment]
Oops. Your memory is better than mine. Thank you!

**Comment by argiepiano** [comment]
The cause is that Feeds adds Entity Plus properties to the Rules configurations. I think I have a fix in mind, I just need to test it and do a new release.

**Comment by argiepiano** [comment]
@nattywebdev can you please test the dev version of the module? You'll need to manually download it and place it in your `modules` folder. 
https://github.com/backdrop-contrib/rules_cmi/archive/refs/heads/1.x-1.x.zip

**Comment by argiepiano** [comment]
Reopening while I wait for you to test.

**Comment by nattywebdev** [comment]
Will do that this afternoon. Thanks @argiepiano

**Comment by nattywebdev** [comment]
Now tested on one site on both development environment and with config imported to live server. The Rules CMI module works fine on both and there is no more report of the error noted above.
Thank you @argiepiano !

**Comment by argiepiano** [comment]
Thanks! Will do a new release.
